development:
  adapter: postgresql
  encoding: unicode
  database: blogdb
  pool: 5      

test:
  adapter: postgresql
  encoding: unicode
  database: blogdb_test
  pool: 5      

production:
  adapter: postgresql
  encoding: unicode
  database: blogdb
  pool: 5    
